# Конфигурация сборки
[build]
  # Команда, которую Netlify выполнит для сборки вашего сайта.
  command = "npm run build"

  # Папка, которую Netlify опубликует.
  # Vite соберет ваше приложение из папки 'client' в папку 'client/dist'.
  publish = "dist/public"

# Правило для корректной работы роутинга в React

[[redirects]]
  from = "/api/*"
  to = "https://directus-production-6ce1.up.railway.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
