# Конфигурация сборки
[build]
  # Команда, которую Netlify выполнит для сборки вашего сайта.
  command = "npm run build"

  # Папка, которую Netlify опубликует.
  # Vite соберет ваше приложение из папки 'client' в папку 'client/dist'.
  publish = "dist/"

# Правило для корректной работы роутинга в React
[[redirects]]
  from = "/api/directus-cases"
  to = "https://directus-production-6ce1.up.railway.app/items/case_studies"
  status = 200
  force = true

[[redirects]]
  from = "/api/directus-blog"
  to = "https://directus-production-6ce1.up.railway.app/items/blog_posts"
  status = 200
  force = true
  
[[redirects]]
  from = "/api/*"
  to = "https://directus-production-6ce1.up.railway.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
