# Конфигурация сборки
[build]
  # Команда, которую Netlify выполнит для сборки вашего сайта.
  command = "npm run build"

  # Папка, которую Netlify опубликует.
  # Vite соберет ваше приложение из папки 'client' в папку 'client/dist'.
  publish = "dist/public"

# Правило для корректной работы роутинга в React
[[redirects]]
  from = "/api/directus-cases"
  to = "https://directus-production-6ce1.up.railway.app/items/case_studies"
  status = 200
  force = true

[[redirects]]
  from = "/api/directus-blog"
  to = "https://directus-production-6ce1.up.railway.app/items/blog_posts"
  status = 200
  force = true
  
[[redirects]]
  from = "/api/*"
  to = "https://directus-production-6ce1.up.railway.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/%D0%AD%D0%BA%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-%D0%BF%D0%B0%D1%81%D0%BF%D0%BE%D1%80%D1%82/"
  to = "/services/ecological-passport"
  status = 301
  force = true

[[redirects]]
  from = "/%D0%9F%D0%B0%D1%81%D0%BF%D0%BE%D1%80%D1%82-%D0%93%D0%9E%D0%A3/"
  to = "/services/gas-treatment-passport"
  status = 301
  force = true

[[redirects]]
  from = "/%D0%98%D0%BD%D0%B2%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%B2%D1%8B%D0%B1%D1%80%D0%BE%D1%81%D0%BE%D0%B2/"
  to = "/services/emissions-inventory"
  status = 301
  force = true

[[redirects]]
  from = "/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82-%D0%BD%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D0%B2%D0%BE%D0%B2-%D0%9F%D0%94%D0%92/"
  to = "/services/pdv-standards"
  status = 301
  force = true

[[redirects]]
  from = "/%D0%9A%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82%D1%8B/"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/%D0%96%D1%83%D1%80%D0%BD%D0%B0%D0%BB%D1%8B-%D0%9F%D0%9E%D0%94-1-2-3/"
  to = "/services/environmental-journals"
  status = 301
  force = true

[[redirects]]
  from = "/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F-%D0%BF%D0%BE-%D0%BE%D0%B1%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%B8%D1%8E-%D1%81-%D0%BE%D1%82%D1%85%D0%BE%D0%B4%D0%B0%D0%BC%D0%B8/"
  to = "/services/waste-management-instructions"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
