# Конфигурация сборки
[build]
  # Команда, которую Netlify выполнит для сборки вашего сайта.
  command = "npm run build"

  # Папка, которую Netlify опубликует.
  # Vite соберет ваше приложение из папки 'client' в папку 'client/dist'.
  publish = "dist/public"

# Правило для корректной работы роутинга в React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "client/dist"
  autoLaunch = true

[[redirects]]
  from = "/api/blog"
  to = "/.netlify/functions/blog"
  status = 200

[[redirects]]
  from = "/api/cases"
  to = "/.netlify/functions/cases"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
